# Generated by Django 3.2.9 on 2021-12-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0002_alter_mmodel_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmodel',
            name='primary_id_is',
            field=models.CharField(blank=True, choices=[('serial_number', 'Serial Number'), ('service_number', 'Service Number'), ('asset_number', 'Asset Number'), ('common_name', 'Common Name')], help_text='By default, the field which should be used as the primary ID field (ex: "SN", "Tag Number", etc)', max_length=50, verbose_name='Primary ID Field'),
        ),
    ]
