# Generated by Django 3.2.9 on 2021-12-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0003_alter_mmodel_primary_id_is'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='primary_id_is',
            new_name='primary_id_field',
        ),
        migrations.RenameField(
            model_name='mmodel',
            old_name='primary_id_is',
            new_name='primary_id_field',
        ),
    ]
