# Generated by Django 3.2.9 on 2021-12-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0005_delete_vista'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemNote',
            new_name='TimelyNote',
        ),
    ]
