# Generated by Django 3.2.9 on 2021-12-22 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0006_rename_itemnote_timelynote'),
    ]

    operations = [
        migrations.CreateModel(
            name='UntimedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The text of the note', verbose_name='text')),
                ('subject', models.CharField(blank=True, help_text='The subject of the note', max_length=50, verbose_name='subject')),
                ('is_major', models.BooleanField(default=False, help_text='If this note should be displayed by default (if not then displayed when "show all notes" is selected)', verbose_name='is major')),
                ('item', models.ForeignKey(help_text='The item to which this note applies', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libtekin.item')),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
    ]
