# Generated by Django 3.2.9 on 2021-12-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0007_untimednote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mmodelcategory',
            options={'ordering': ['sort_name']},
        ),
    ]
