# Generated by Django 3.2.9 on 2021-12-25 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0008_alter_mmodelcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='latest_inventory',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='The date that this item was last confirmed in inventory', null=True, verbose_name='Latest Inventory Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='primary_id_field',
            field=models.CharField(blank=True, choices=[('serial_number', 'Serial Number'), ('service_number', 'Service Number'), ('asset_number', 'Asset Number'), ('barcode', 'Barcode')], help_text='The identifier which is the primary id', max_length=50, verbose_name='primary id is'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='primary_id_field',
            field=models.CharField(blank=True, choices=[('serial_number', 'Serial Number'), ('service_number', 'Service Number'), ('asset_number', 'Asset Number'), ('barcode', 'Barcode')], help_text='By default, the field which should be used as the primary ID field (ex: "SN", "Tag Number", etc)', max_length=50, verbose_name='Primary ID Field'),
        ),
    ]
