# Generated by Django 3.2.9 on 2021-12-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0009_auto_20211225_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(blank=True, help_text="Can be blank for notes that don't represent events.  If filled, consider the effective date of the information rather than the date the note was made", null=True, verbose_name='when')),
                ('text', models.CharField(blank=True, help_text='The text of the note.  Can be a subject line or introduction if more is included in details', max_length=125)),
                ('details', models.TextField(help_text='The details of the note if the summary is not sufficient', verbose_name='details')),
                ('is_major', models.BooleanField(default=False, help_text='If this note is diplayed by default in the item detail view.  If not, it will be displayed when "Show All" is selected', verbose_name='is major or current status')),
                ('item', models.ForeignKey(help_text='The item to which this note applies', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libtekin.item')),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
    ]
