# Generated by Django 3.2.9 on 2021-12-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0011_itemnote_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='untimednote',
            name='item',
        ),
        migrations.AlterModelOptions(
            name='itemnote',
            options={'ordering': ['-when', 'text']},
        ),
        migrations.DeleteModel(
            name='TimelyNote',
        ),
        migrations.DeleteModel(
            name='UntimedNote',
        ),
    ]
