# Generated by Django 3.2.9 on 2021-12-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0012_auto_20211226_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnote',
            name='details',
            field=models.TextField(blank=True, help_text='The details of the note if the summary is not sufficient', verbose_name='details'),
        ),
    ]
