# Generated by Django 3.2.9 on 2022-01-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0013_alter_itemnote_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['primary_id']},
        ),
    ]
