# Generated by Django 3.2.9 on 2022-02-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0015_auto_20220201_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemnote',
            old_name='is_major',
            new_name='is_current',
        ),
    ]
