# Generated by Django 3.2.9 on 2022-04-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0018_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'Removed from Inventory'), (1, 'Not Yet Received'), (2, 'Awaiting Removal'), (3, 'Stored'), (10, 'Ready'), (11, 'In Use')], default=11, help_text='The status of this item', verbose_name='status'),
        ),
    ]
