# Generated by Django 3.2.9 on 2022-05-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0022_populate_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='status',
            new_name='status_old',
        ),
    ]
