# Generated by Django 3.2.9 on 2022-05-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0023_rename_status_item_status_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='status_new',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status_old',
        ),
    ]
