# Generated by Django 3.2.9 on 2022-05-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0024_auto_20220514_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('list_position', 'name')},
        ),
        migrations.RenameField(
            model_name='status',
            old_name='list_order',
            new_name='list_position',
        ),
    ]
