# Generated by Django 3.2.9 on 2022-05-26 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0025_auto_20220515_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='installation_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='The date that this item was installed', null=True, verbose_name='Installation Date'),
        ),
    ]
