# Generated by Django 3.2.9 on 2022-05-26 10:43

from django.db import migrations, models
import django.db.models.deletion
import libtekin.models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0027_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.ForeignKey(default=libtekin.models.get_default_status, help_text='The status of this project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libtekin.status'),
        ),
    ]
