# Generated by Django 4.1 on 2022-09-03 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0028_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnote',
            name='when',
            field=models.DateField(blank=True, default=datetime.datetime.now, help_text="Can be blank for notes that don't represent events.  If filled, consider the effective date of the information rather than the date the note was made", null=True, verbose_name='when'),
        ),
    ]
