# Generated by Django 4.1.2 on 2023-01-11 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0029_alter_itemnote_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnote',
            name='when',
            field=models.DateField(blank=True, default=datetime.date.today, help_text="Can be blank for notes that don't represent events.  If filled, consider the effective date of the information rather than the date the note was made", null=True, verbose_name='when'),
        ),
    ]
