# Generated by Django 4.1.2 on 2023-01-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0030_alter_itemnote_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnote',
            name='details',
            field=models.TextField(blank=True, help_text='The details of the note if the summary text is not sufficient', verbose_name='details'),
        ),
    ]
