# Generated by Django 4.1.2 on 2023-01-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0031_alter_itemnote_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemnote',
            options={'ordering': ['-when']},
        ),
        migrations.RemoveField(
            model_name='itemnote',
            name='text',
        ),
        migrations.AddField(
            model_name='itemnote',
            name='maintext',
            field=models.CharField(blank=True, help_text='The text of the note.  Can be a subject line or introduction if more is included in details', max_length=125, verbose_name='description'),
        ),
    ]
