# Generated by Django 4.1.7 on 2023-04-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0033_itemnotecategory_alter_item_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemnote',
            old_name='is_current',
            new_name='is_current_status',
        ),
        migrations.AddField(
            model_name='itemnote',
            name='endtext',
            field=models.CharField(blank=True, help_text='For temporary situations, comments regarding the end of the situation (ex: "memory card replaced")', max_length=125, verbose_name='end comment'),
        ),
        migrations.AlterField(
            model_name='itemnote',
            name='details',
            field=models.TextField(blank=True, help_text='The details of the note if the description text is not sufficient', verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='itemnote',
            name='maintext',
            field=models.CharField(blank=True, help_text='The text of the note.  Optional if a category is chosen and no other details are necessary.', max_length=125, verbose_name='description'),
        ),
    ]
