# Generated by Django 4.1.7 on 2023-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0034_remove_itemnote_is_current_itemnote_endtext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnote',
            name='is_current_status',
            field=models.BooleanField(default=False, help_text='If this note is diplayed by default in the item detail view. That display is also determined by the dates.  If not displayed by default, notes will be displayed when "Show All" is selected', verbose_name='is major or current status'),
        ),
    ]
