# Generated by Django 4.1.7 on 2023-04-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0035_alter_itemnote_is_current_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemnote',
            old_name='is_current_status',
            new_name='is_status',
        ),
    ]
