# Generated by Django 4.1.7 on 2023-04-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0036_rename_is_current_status_itemnote_is_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnote',
            name='is_current',
            field=models.BooleanField(default=False, help_text='If this note displays currently correct information', verbose_name='is current'),
        ),
        migrations.AlterField(
            model_name='itemnote',
            name='is_status',
            field=models.BooleanField(default=False, help_text='If this note is diplayed by default in the item detail view. That display is also determined by the dates.  If not displayed by default, notes will be displayed when "Show All" is selected', verbose_name='is status update'),
        ),
    ]
