# Generated by Django 4.1.7 on 2023-05-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0037_itemnote_is_current_alter_itemnote_is_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnote',
            name='is_current',
            field=models.BooleanField(default=True, help_text='If this note displays currently correct information', verbose_name='is current'),
        ),
    ]
