# Generated by Django 4.1.7 on 2023-05-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0038_alter_itemnote_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnote',
            name='is_current',
            field=models.BooleanField(default=True, help_text='If this note displays current and reportable information. Uncheck for on-off notes like "Updated Windows", for low importance notes like "Formerly human resources laptop", and for statuses like "Failing Hard Drive" when resolved or longer valid', verbose_name='is current'),
        ),
        migrations.AlterField(
            model_name='itemnote',
            name='is_status',
            field=models.BooleanField(default=False, help_text='If this note represents a situational status ex: "At Shop for Repair", "On Loan to Event Committee"', verbose_name='is status update'),
        ),
    ]
