# Generated by Django 4.1.7 on 2023-05-01 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0039_alter_itemnote_is_current_alter_itemnote_is_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnote',
            name='is_current',
            field=models.BooleanField(default=True, help_text='If this note displays current and reportable information. Uncheck for one-off notes like "Updated Windows", for low importance notes like "Formerly human resources laptop", and for statuses like "Failing Hard Drive" when resolved or longer valid', verbose_name='is current'),
        ),
        migrations.AlterField(
            model_name='itemnote',
            name='when',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='The effective date of the information in the note ( rather than the date the note was made )', null=True, verbose_name='when'),
        ),
    ]
