# Generated by Django 4.1.7 on 2023-05-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0040_alter_itemnote_is_current_alter_itemnote_when'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNoteLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the level', max_length=50)),
                ('number', models.IntegerField(default=0, help_text='The value of the level, with 0 being info only and a higher number, such as 5 being critical', verbose_name='numeric value')),
            ],
            options={
                'ordering': ('number', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='status',
            name='is_active',
            field=models.BooleanField(default=False, help_text='If this status is for an active item)', verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If this is the default status for new items (Only one will used even if more than one is selected)', verbose_name='is default'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(help_text='The status of the item', max_length=50),
        ),
    ]
