# Generated by Django 4.1.7 on 2023-05-02 14:33

from django.db import migrations, models
import django.db.models.deletion
import libtekin.models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0041_itemnotelevel_alter_status_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnote',
            name='level',
            field=models.ForeignKey(default=libtekin.models.get_default_level, help_text='The level of this note', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libtekin.itemnotelevel'),
        ),
    ]
