# Generated by Django 4.1.7 on 2023-05-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0042_itemnote_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemnote',
            name='is_status',
        ),
    ]
