# Generated by Django 4.2.4 on 2023-08-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0043_remove_itemnote_is_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnote',
            name='is_current',
            field=models.BooleanField(default=True, help_text='If this note displays current and reportable information. Uncheck for one-off notes like "Updated Windows", for low importance notes like "Formerly human resources laptop", and for statuses like "Failing Hard Drive" when resolved or longer valid', verbose_name='display as status'),
        ),
    ]
