# Generated by Django 4.2.4 on 2023-09-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0045_remove_itemnote_is_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemnotelevel',
            name='view_by_default',
        ),
        migrations.AddField(
            model_name='itemnotelevel',
            name='flagged',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='If notes of this level are flagged for viewing by default in an item detail view', verbose_name='flagged'),
        ),
    ]
