# Generated by Django 4.2.4 on 2023-09-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0046_remove_itemnotelevel_view_by_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemnotelevel',
            name='flagged',
        ),
        migrations.AddField(
            model_name='itemnote',
            name='flagged',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='If this note is flagged for viewing by default in an item detail view', verbose_name='flagged'),
        ),
    ]
