# Generated by Django 4.2.4 on 2023-10-04 14:38

import datetime
from django.db import migrations, models
from ..models import Entity
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "libtekin",
            "0001_squashed_0047_remove_itemnotelevel_flagged_itemnote_flagged",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemAssignee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "when",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        help_text="The effective date of the assignment",
                        null=True,
                        verbose_name="when",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        help_text="The person or group to whom the item was assigned",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="libtekin.entity",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The item to which assignment applies",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="libtekin.item",
                    ),
                ),
            ],
            options={"ordering": ["-when"]},
        ),
        migrations.CreateModel(
            name="ItemBorrower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "when",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        help_text="The effective date of the loan",
                        null=True,
                        verbose_name="when",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="The person or group to whom the item was lent.  This can be set to None to indicate that the previous borrower returned it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="libtekin.entity",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The item to which this loan applies",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="libtekin.item",
                    ),
                ),
            ],
            options={"ordering": ["-when"]},
        ),
    ]
