# Generated by Django 4.2.4 on 2023-10-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0050_alter_itemassignee_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='condition',
        ),
        migrations.AlterField(
            model_name='itemnote',
            name='itemnotecategory',
            field=models.ForeignKey(help_text='The category for this note', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libtekin.itemnotecategory', verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
