# Generated by Django 4.2.4 on 2023-10-31 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0051_remove_item_condition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemassignee',
            options={'ordering': ['-when', '-pk']},
        ),
    ]
