# Generated by Django 4.2.4 on 2023-11-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0052_alter_itemassignee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemborrower',
            options={'ordering': ['-when', '-pk']},
        ),
    ]
