# Generated by Django 4.2.4 on 2023-12-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0053_alter_itemborrower_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='primary_id_field',
            field=models.CharField(blank=True, help_text='The identifier which is the primary id', max_length=50, verbose_name='primary id is'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='primary_id_field',
            field=models.CharField(blank=True, help_text='By default, the field which should be used as the primary ID field (ex: "SN", "Tag Number", etc)', max_length=50, verbose_name='Primary ID Field'),
        ),
    ]
