# Generated by Django 4.2.4 on 2024-02-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libtekin", "0054_alter_item_primary_id_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="essid",
            field=models.CharField(
                blank=True,
                help_text="The device's IMEI, MEID, SSID, etc..",
                max_length=100,
                verbose_name="ESSID",
            ),
        ),
        migrations.RenameField(
            model_name="item",
            old_name="essid",
            new_name="mobile_id",
        ),
    ]
