# Generated by Django 4.2.4 on 2024-02-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0055_remove_item_essid_item_mobile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mobile_id',
            field=models.CharField(blank=True, help_text="The device's IMEI, MEID, SSID, etc..", max_length=100, verbose_name='Mobile ID'),
        ),
    ]
