# Generated by Django 4.2.4 on 2024-02-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0056_alter_item_mobile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sim_iccid',
            field=models.CharField(blank=True, help_text='The id of the SIM card', max_length=100, verbose_name='SIM iccid'),
        ),
    ]
