# Generated by Django 5.0.3 on 2024-04-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0057_item_sim_iccid'),
        ('spl_members', '0002_alter_department_options_alter_jobposition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='spl_member_assignee',
            field=models.ForeignKey(blank=True, help_text='The responsible party for the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_assigned_to_member', to='spl_members.member', verbose_name='member assignee'),
        ),
        migrations.AddField(
            model_name='item',
            name='spl_member_borrower',
            field=models.ForeignKey(blank=True, help_text='The temporary user of the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_borrowed_to_member', to='spl_members.member', verbose_name='member borrower'),
        ),
        migrations.AddField(
            model_name='itemassignee',
            name='spl_member_assignee',
            field=models.ForeignKey(blank=True, help_text='The current responsible party for the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_assigned', to='spl_members.member', verbose_name='member assignee'),
        ),
        migrations.AddField(
            model_name='itemborrower',
            name='spl_member_borrower',
            field=models.ForeignKey(blank=True, help_text='The current user of the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_borrowed_by_member', to='spl_members.member', verbose_name='member borrower'),
        ),
        migrations.AlterField(
            model_name='item',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='The responsible party for the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_assigned', to='libtekin.entity', verbose_name='assignee'),
        ),
        migrations.AlterField(
            model_name='item',
            name='borrower',
            field=models.ForeignKey(blank=True, help_text='The temporary user of the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_borrowed', to='libtekin.entity', verbose_name='borrower'),
        ),
    ]
