# Generated by Django 5.0.3 on 2024-04-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0059_populate_spl_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='item',
            name='borrower',
        ),
    ]
