# Generated by Django 5.0.3 on 2024-04-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0060_remove_item_assignee_remove_item_borrower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='spl_member_assignee',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='spl_member_borrower',
            new_name='borrower',
        ),
        migrations.RenameField(
            model_name='itemassignee',
            old_name='spl_member_assignee',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='itemborrower',
            old_name='spl_member_borrower',
            new_name='borrower',
        ),
        migrations.RemoveField(
            model_name='itemassignee',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='itemborrower',
            name='entity',
        ),
    ]
