# Generated by Django 5.0.3 on 2024-05-03 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0061_rename_spl_member_assignee_item_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemassignee',
            name='when',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The effective date of the assignment', null=True, verbose_name='when'),
        ),
    ]
