# Generated by Django 5.0.3 on 2024-05-11 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0062_alter_itemassignee_when'),
        ('spl_members', '0004_alter_member_options_alter_member_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemassignee',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='The current responsible party for the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_assignements', to='spl_members.member', verbose_name='member assignee'),
        ),
        migrations.AlterField(
            model_name='itemassignee',
            name='item',
            field=models.ForeignKey(help_text='The item to which assignment applies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_assignements', to='libtekin.item'),
        ),
        migrations.AlterField(
            model_name='itemborrower',
            name='borrower',
            field=models.ForeignKey(blank=True, help_text='The user of the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_borrow', to='spl_members.member', verbose_name='member borrower'),
        ),
        migrations.AlterField(
            model_name='itemborrower',
            name='item',
            field=models.ForeignKey(help_text='The item to which this loan applies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_borrow', to='libtekin.item'),
        ),
    ]
