# Generated by Django 5.0.6 on 2024-10-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin', '0063_alter_itemassignee_assignee_alter_itemassignee_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='service_number',
        ),
        migrations.AddField(
            model_name='item',
            name='bios_serial_number',
            field=models.CharField(blank=True, help_text='The serial number stored in bios used by several computer manufacturers', max_length=100, verbose_name='bios serial number'),
        ),
        migrations.AlterField(
            model_name='item',
            name='primary_id_field',
            field=models.CharField(blank=True, help_text='The identifier which is the primary id', max_length=50, verbose_name='primary id field'),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, help_text='The serial number or alternate ID which is used as the serial number', max_length=100, verbose_name='serial number'),
        ),
    ]
